var found = true;
var grade = 88.6;
var firstName = "Rohan";
var lastName = "Jadhav";
var common = "string";
common = 1;
console.log("hai" + " " + firstName + " " + lastName);
console.log(found);
console.log("the grade is " + grade);
console.log("any has value: ".concat(common));
console.log("hai ".concat(firstName, " ").concat(lastName));
