"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Circle_1 = require("./Circle");
var Shape_1 = require("./Shape");
var Rectangle_1 = require("./Rectangle");
var myShape = new Shape_1.Shape(10, 30);
console.log(myShape.getInfo());
var myCircle = new Circle_1.Circle(5, 10, 15);
console.log(myCircle.getInfo());
var myRectangle = new Rectangle_1.Rectangle(10, 20, 30, 40);
console.log(myRectangle.getInfo());
